-- MySQL Script generated by MySQL Workbench
-- Thu Jul 31 12:12:05 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema registro_alumno_qr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema registro_alumno_qr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `registro_alumno_qr` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `registro_alumno_qr` ;

-- -----------------------------------------------------
-- Table `registro_alumno_qr`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro_alumno_qr`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `registro_alumno_qr`.`alumnos` (
  `id_alumno` INT NOT NULL,
  `matricula` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NOT NULL,
  `a_paterno` VARCHAR(255) NOT NULL,
  `a_materno` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `QR` VARCHAR(255) NOT NULL,
  `email_verficado_hora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creado_hora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `modificado_hora` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_alumno`),
  UNIQUE INDEX `id_alumno_UNIQUE` (`id_alumno` ASC) VISIBLE)
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `registro_alumno_qr`.`asistencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `registro_alumno_qr`.`asistencias` ;

CREATE TABLE IF NOT EXISTS `registro_alumno_qr`.`asistencias` (
  `id` INT NOT NULL,
  `alumno_id` INT NOT NULL,
  `dia_asistencia` DATE NOT NULL,
  `hora_entrada` TIMESTAMP NOT NULL,
  `hora_salida` TIMESTAMP NULL DEFAULT NULL,
  `hora_actualizacion` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
